apiVersion: v1
kind: Service
metadata:
  name: product-catalogue-service
spec:
  selector:
    app: product-catalogue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer